# Generated by Django 4.2.2 on 2023-07-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
