# Generated by Django 4.2.2 on 2023-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0002_alter_customer_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_installation',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
