# Generated by Django 4.2.2 on 2023-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0003_alter_customer_date_of_installation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_of_purchase',
            new_name='amc_upto_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact_details',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='amc_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='machine_model',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
