# Generated by Django 4.2.2 on 2023-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0004_rename_date_of_purchase_customer_amc_upto_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amc_status',
            field=models.CharField(max_length=10),
        ),
    ]
