# Generated by Django 4.2.2 on 2023-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0005_alter_customer_amc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amc_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
